nombre = input("Ingresa tu nombre: ")
apellido = input("Ingresa tu apellido: ")
codigo_seccion = input("Ingresa tu código-sección: ")
sede = input("Ingresa tu sede: ")

print("\nInformación ingresada:")
print("Nombre:", nombre)
print("Apellido:", apellido)
print("Código-sección:", codigo_seccion)
print("Sede:", sede)
